# Generated by Django 4.1.1 on 2023-01-15 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_stripe_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='bonus',
            field=models.FloatField(default=0),
        ),
    ]
